# Site settings
title: Misc. notes on random topics
#email: your-email@domain.com
description: "Misc. notes on random topics."
baseurl: ""
url: "http://t-w.github.io"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

