# Site settings
title: Messy notes (uBlog)
#email: your-email@domain.com
description: "Messy notes on software/programming."
baseurl: ""
url: "http://t-w.github.io"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

