# Site settings
title: Messy notes on random topics
#email: your-email@domain.com
description: "Messy notes on random (often computing) matters."
baseurl: ""
url: "http://t-w.github.io"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

